### ISSUE TITLE
Threshold slider number inputs act funny

### ISSUE THREAD

**Issue by cjdenio** [Chameleon-Vision/chameleon-vision#51] opened 2020-01-21 01:42 UTC
The title pretty much sums it up. Namely, when I hit Backspace inside the Max number input, the Min input changes its value. :thinking:

**Comment by oriagranat9** [comment] 2020-01-25 11:15
what where the values when you hit backspace

**Comment by Bankst** [comment] 2020-05-26 07:01
Closing due to no reply. Please re-open this issue if you are still able to reproduce this.

**Closed by Bankst** 2020-05-26 07:01 UTC
